[workspace]
members = [
    "examples/rust", # 1.11.0+solana.1.17.4
    "yellowstone-grpc-client", # 1.12.0+solana.1.17.4
    "yellowstone-grpc-geyser", # 1.11.0+solana.1.17.4
    "yellowstone-grpc-proto", # 1.11.0+solana.1.17.4
    "yellowstone-grpc-tools", # 1.0.0-rc.6+solana.1.17.4
]

[profile.release]
debug = true
lto = true
codegen-units = 1
