[workspace]
resolver = "2"
members = [
    "examples/rust", # 1.11.0+solana.1.16.19
    "yellowstone-grpc-client", # 1.12.0+solana.1.16.19
    "yellowstone-grpc-geyser", # 1.11.0+solana.1.16.19
    "yellowstone-grpc-proto", # 1.11.0+solana.1.16.19
    "yellowstone-grpc-tools", # 1.0.0-rc.6+solana.1.16.19
]

[workspace.package]
authors = ["Triton One"]
edition = "2021"
homepage = "https://triton.one"
repository = "https://github.com/rpcpool/yellowstone-grpc"
license = "Apache-2.0"
keywords = ["solana"]

[workspace.dependencies]
solana-account-decoder = "=1.16.19"
solana-geyser-plugin-interface = "=1.16.19"
solana-logger = "=1.16.19"
solana-sdk = "=1.16.19"
solana-transaction-status = "=1.16.19"

[profile.release]
debug = true
lto = true
codegen-units = 1

[patch.crates-io]
solana-account-decoder = { git = "https://github.com/rpcpool/solana-public.git", tag = "v1.16.19-geyser-block-v3" }
solana-geyser-plugin-interface = { git = "https://github.com/rpcpool/solana-public.git", tag = "v1.16.19-geyser-block-v3" }
solana-logger = { git = "https://github.com/rpcpool/solana-public.git", tag = "v1.16.19-geyser-block-v3" }
solana-program = { git = "https://github.com/rpcpool/solana-public.git", tag = "v1.16.19-geyser-block-v3" }
solana-sdk = { git = "https://github.com/rpcpool/solana-public.git", tag = "v1.16.19-geyser-block-v3" }
solana-transaction-status = { git = "https://github.com/rpcpool/solana-public.git", tag = "v1.16.19-geyser-block-v3" }
