[package]
name = "yellowstone-grpc-proto"
version = "2.0.0"
authors = { workspace = true }
edition = { workspace = true }
description = "Yellowstone gRPC Geyser Protobuf Definitions"
homepage = { workspace = true }
repository = { workspace = true }
license = "Apache-2.0"
keywords = { workspace = true }
publish = true

[dependencies]
agave-geyser-plugin-interface = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
prost = { workspace = true }
smallvec = { workspace = true, optional = true }
solana-account-decoder = { workspace = true, optional = true }
solana-sdk = { workspace = true, optional = true }
solana-transaction-status = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tonic = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
protobuf-src = { workspace = true }
tonic-build = { workspace = true }

[features]
convert = ["dep:bincode", "dep:solana-account-decoder", "dep:solana-sdk", "dep:solana-transaction-status"]
geyser_weak = [
    "convert",
    "dep:agave-geyser-plugin-interface",
    "dep:bytes",
    "dep:smallvec",
    "dep:solana-sdk",
    "dep:solana-transaction-status",
    "dep:thiserror"
]
tonic-compression = ["tonic/gzip", "tonic/zstd"]
default = ["convert", "tonic-compression"]

[lints]
workspace = true
